import React from "react";
import {
  FaGithub,
  FaExternalLinkAlt,
  FaInfoCircle,
  FaPython,
  FaDocker,
  FaReact,
  FaBootstrap,
  FaToolbox,
} from "react-icons/fa";
import {
  SiPypi,
  SiDjango,
  SiPerl,
  SiGnubash,
  SiGnu,
  SiJavascript,
  SiMui,
  SiAnaconda,
  SiGithubactions,
  SiFirebase,
  SiRender,
  SiAxios,
  SiGooglecloud,
  SiTensorflow,
  SiScikitlearn,
} from "react-icons/si";
import { FcWorkflow } from "react-icons/fc";
import { TbApi } from "react-icons/tb";
import { PiBracketsCurlyBold } from "react-icons/pi";
import "./Projects.css";

const projects = [
  {
    name: "varsnap",
    description:
      "A web application for visualization of human genetic variants in protein domain and transcript context.",
    demo: "https://varsnap.onrender.com/",
    coldStartNote:
      "Hosted on Render free tier, it may take ~30s to wake up on first load.",
    technologies: ["Python", "Django", "JavaScript", "FaBootstrap", "SiRender"],
  },
  {
    name: "nf-rna-wasp-allele-count",
    description:
      "A genotype-aware RNA-seq pipeline using STAR+WASP for allele-specific read counting and variant allele fraction estimation.",
    repo: "https://github.com/maurya-anand/nf-rna-wasp-allele-count",
    technologies: ["Nextflow", "Docker", "SiGithubactions"],
  },
  {
    name: "nf-ont-methpro",
    description:
      "A haplotype-resolved DNA methylation profiling pipeline for Oxford Nanopore long-read sequencing.",
    repo: "https://github.com/maurya-anand/nf-ont-methpro",
    technologies: ["Nextflow", "Docker", "SiGithubactions"],
  },
  {
    name: "gene-to-protein-domains",
    description:
      "A command-line utility to fetch protein domain and transcript information via UniProt/Ensembl APIs.",
    repo: "https://github.com/maurya-anand/gene-to-protein-domains",
    technologies: ["Python"],
  },
  {
    name: "proteomics-ML-workflow",
    description:
      "A cloud-based proteomics machine learning workflow using deep learning and classical ML models for biomarker discovery.",
    demo: "https://dockstore.org/workflows/github.com/anand-imcm/proteomics-ML-workflow",
    repo: "https://github.com/anand-imcm/proteomics-ML-workflow",
    technologies: [
      "PiBracketsCurlyBold",
      "Python",
      "SiTensorflow",
      "SiScikitlearn",
      "Docker",
      "SiGithubactions",
      "SiGooglecloud",
    ],
  },
  {
    name: "Gauchian-enrich",
    description:
      "A variant annotator for GBA variants called by the Illumina Gauchian tool.",
    repo: "https://github.com/maurya-anand/gauchian-enrich",
    technologies: ["Perl", "Make", "Docker", "SiGithubactions"],
  },
  {
    name: "wgs-varcall",
    description:
      "A cloud-based WGS variant calling pipeline for short-read (Illumina) data with an additional feature for targeted GBA variant detection using the Illumina Gauchian tool.",
    demo: "https://dockstore.org/workflows/github.com/anand-imcm/wgs-varcall",
    repo: "https://github.com/anand-imcm/wgs-varcall",
    technologies: [
      "PiBracketsCurlyBold",
      "Docker",
      "SiGithubactions",
      "SiGooglecloud",
    ],
  },
  {
    name: "getBamDepth",
    description:
      "A tool to generate depth of coverage from a BAM/SAM/CRAM file or parse the output generated by samtools depth.",
    repo: "https://github.com/maurya-anand/getBamDepth",
    technologies: ["Perl", "SiGithubactions"],
  },
  {
    name: "variant-liftover",
    description:
      "A command-line tool to lift over SNVs/indels from hg19 to hg38.",
    repo: "https://github.com/maurya-anand/liftover",
    technologies: ["Make", "Python", "Docker", "SiGithubactions"],
  },
  {
    name: "pb-variant-call",
    description:
      "A WDL-based workflow for variant calling and annotation using PacBio HiFi long-read sequencing data, optimized for execution on the Terra.bio cloud platform.",
    demo: "https://dockstore.org/workflows/github.com/anand-imcm/pb-variant-call",
    repo: "https://github.com/anand-imcm/pb-variant-call",
    technologies: [
      "PiBracketsCurlyBold",
      "Python",
      "Perl",
      "Docker",
      "SiGithubactions",
      "SiGooglecloud",
    ],
  },
  {
    name: "ARA (Automatic Record Analysis)",
    description:
      "A pipeline for automated exploration of NCBI SRA datasets using nucleotide sequences as queries.",
    repo: "https://github.com/maurya-anand/ARA",
    demo: "https://workflowhub.eu/workflows/546",
    technologies: [
      "Perl",
      "FaToolbox",
      "Docker",
      "SiAnaconda",
      "SiGithubactions",
    ],
  },
  {
    name: "SRA-annotator",
    description:
      "A command-line tool for retrieving annotations from the NCBI SRA database.",
    repo: "https://github.com/maurya-anand/sra-annotator",
    technologies: ["Python", "NCBIApi"],
  },
];

const technologyIcons = {
  Python: <FaPython className="technology-icon" title="Python" />,
  Docker: <FaDocker className="technology-icon" title="Docker" />,
  ReactJS: <FaReact className="technology-icon" title="ReactJS" />,
  Django: <SiDjango className="technology-icon" title="Django" />,
  Perl: <SiPerl className="technology-icon" title="Perl" />,
  Bash: <SiGnubash className="technology-icon" title="Bash" />,
  Make: <SiGnu className="technology-icon" title="GNU Make" />,
  JavaScript: <SiJavascript className="technology-icon" title="JavaScript" />,
  MUI: <SiMui className="technology-icon" title="Material UI" />,
  SiAnaconda: <SiAnaconda className="technology-icon" title="Mamba" />,
  SiGithubactions: (
    <SiGithubactions className="technology-icon" title="Github Actions" />
  ),
  FaBootstrap: <FaBootstrap className="technology-icon" title="Bootstrap" />,
  SiFirebase: <SiFirebase className="technology-icon" title="Firebase" />,
  SiRender: <SiRender className="technology-icon" title="Render" />,
  SiAxios: <SiAxios className="technology-icon" title="Axios" />,
  NCBIApi: <TbApi className="technology-icon" title="NCBI Entrez" />,
  TbApi: <TbApi className="technology-icon" title="NCBI Entrez" />,
  FaToolbox: <FaToolbox className="technology-icon" title="NCBI SRA toolkit" />,
  PiBracketsCurlyBold: (
    <PiBracketsCurlyBold
      className="technology-icon"
      title="Workflow Description Language (WDL)"
    />
  ),
  Nextflow: <FcWorkflow className="technology-icon" title="Nextflow" />,
  SiGooglecloud: (
    <SiGooglecloud className="technology-icon" title="Terra.bio on GCP" />
  ),
  SiTensorflow: <SiTensorflow className="technology-icon" title="Tensorflow" />,
  SiScikitlearn: (
    <SiScikitlearn className="technology-icon" title="Scikitlearn" />
  ),
};

const Projects = () => (
  <section className="section-container">
    <h2 className="centered-header">Projects</h2>
    <div className="projects-grid">
      {projects.map((project, index) => (
        <div key={index} className="project-card card">
          <h3 className="project-title">{project.name}</h3>
          <p className="project-description">{project.description}</p>
          <div className="project-technologies">
            {project.technologies.map((tech, idx) => (
              <span key={idx} className="technology-icon-wrapper">
                {technologyIcons[tech]}
              </span>
            ))}
          </div>
          <div className="project-links">
            {project.demo && (
              <a
                href={project.demo}
                target="_blank"
                rel="noopener noreferrer"
                className={`project-link${project.coldStartNote ? " has-cold-start-tooltip" : ""}`}
                data-tooltip={project.coldStartNote || undefined}
              >
                <FaExternalLinkAlt /> Demo
                {project.coldStartNote && (
                  <FaInfoCircle className="cold-start-icon" />
                )}
              </a>
            )}
            {project.pypi && (
              <a
                href={project.pypi}
                target="_blank"
                rel="noopener noreferrer"
                className="project-link"
              >
                <SiPypi /> PyPI
              </a>
            )}
            {project.repo && (
              <a
                href={project.repo}
                target="_blank"
                rel="noopener noreferrer"
                className="project-link"
              >
                <FaGithub /> Source
              </a>
            )}
          </div>
        </div>
      ))}
    </div>
  </section>
);

export default Projects;
