import {
  FaGithub,
  FaExternalLinkAlt,
  FaPython,
  FaDocker,
  FaBootstrap,
  FaToolbox,
} from "react-icons/fa";
import {
  SiDjango,
  SiPerl,
  SiGnu,
  SiJavascript,
  SiAnaconda,
  SiGithubactions,
  SiRender,
  SiGooglecloud,
  SiTensorflow,
  SiScikitlearn,
} from "react-icons/si";
import { FcWorkflow } from "react-icons/fc";
import { TbApi } from "react-icons/tb";
import { PiBracketsCurlyBold } from "react-icons/pi";
import "./Projects.css";

const projects = [
  {
    name: "SnapVar",
    description:
      "A web application for visualisation of human genetic variants in protein domain and transcript context.",
    demo: "https://snapvar.onrender.com",
    coldStartNote:
      "Demo: Hosted on Render free tier, it may take ~30s to wake up on first load.",
    technologies: ["Python", "Django", "JavaScript", "Bootstrap", "Render"],
  },
  {
    name: "BiomarkerML",
    description:
      "A cloud-based proteomics machine learning workflow using deep learning and classical ML models for biomarker discovery.",
    demo: "https://dockstore.org/workflows/github.com/anand-imcm/proteomics-ML-workflow",
    repo: "https://github.com/anand-imcm/proteomics-ML-workflow",
    technologies: [
      "WDL",
      "Python",
      "TensorFlow",
      "scikit-learn",
      "Docker",
      "GitHub Actions",
      "Terra.bio (GCP)",
    ],
  },
  {
    name: "ARA (Automatic Record Analysis)",
    description:
      "A pipeline for automated exploration of NCBI SRA datasets using nucleotide sequences as queries.",
    repo: "https://github.com/maurya-anand/ARA",
    demo: "https://workflowhub.eu/workflows/546",
    technologies: [
      "Perl",
      "NCBI SRA Toolkit",
      "Docker",
      "Mamba",
      "GitHub Actions",
    ],
  },
  {
    name: "nf-rna-wasp-allele-count",
    description:
      "A genotype-aware RNA-seq pipeline using STAR+WASP for allele-specific read counting and variant allele fraction estimation.",
    repo: "https://github.com/maurya-anand/nf-rna-wasp-allele-count",
    technologies: ["Nextflow", "Docker", "GitHub Actions"],
  },
  {
    name: "wgs-varcall",
    description:
      "A cloud-based WGS variant calling pipeline for short-read (Illumina) data with an additional feature for targeted GBA variant detection using the Illumina Gauchian tool.",
    demo: "https://dockstore.org/workflows/github.com/anand-imcm/wgs-varcall",
    repo: "https://github.com/anand-imcm/wgs-varcall",
    technologies: ["WDL", "Docker", "GitHub Actions", "Terra.bio (GCP)"],
  },
  {
    name: "nf-ont-methpro",
    description:
      "A haplotype-resolved DNA methylation profiling pipeline for Oxford Nanopore long-read sequencing.",
    repo: "https://github.com/maurya-anand/nf-ont-methpro",
    technologies: ["Nextflow", "Docker", "GitHub Actions"],
  },
  {
    name: "pb-variant-call",
    description:
      "A WDL-based workflow for variant calling and annotation using PacBio HiFi long-read sequencing data, optimised for execution on the Terra.bio cloud platform.",
    demo: "https://dockstore.org/workflows/github.com/anand-imcm/pb-variant-call",
    repo: "https://github.com/anand-imcm/pb-variant-call",
    technologies: [
      "WDL",
      "Python",
      "Perl",
      "Docker",
      "GitHub Actions",
      "Terra.bio (GCP)",
    ],
  },
  {
    name: "Gauchian-enrich",
    description:
      "A variant annotator for GBA variants called by the Illumina Gauchian tool.",
    repo: "https://github.com/maurya-anand/gauchian-enrich",
    technologies: ["Perl", "Make", "Docker", "GitHub Actions"],
  },
  {
    name: "getBamDepth",
    description:
      "A tool to generate depth of coverage from a BAM/SAM/CRAM file or parse the output generated by samtools depth.",
    repo: "https://github.com/maurya-anand/getBamDepth",
    technologies: ["Perl", "GitHub Actions"],
  },
  {
    name: "variant-liftover",
    description:
      "A command-line tool to lift over SNVs/indels from hg19 to hg38.",
    repo: "https://github.com/maurya-anand/liftover",
    technologies: ["Make", "Python", "Docker", "GitHub Actions"],
  },
  {
    name: "gene-to-protein-domains",
    description:
      "A command-line utility to fetch protein domain and transcript information via UniProt/Ensembl APIs.",
    repo: "https://github.com/maurya-anand/gene-to-protein-domains",
    technologies: ["Python"],
  },
  {
    name: "SRA-annotator",
    description:
      "A command-line tool for retrieving annotations from the NCBI SRA database.",
    repo: "https://github.com/maurya-anand/sra-annotator",
    technologies: ["Python", "NCBI Entrez API"],
  },
];

const technologyIcons = {
  Python: <FaPython />,
  Docker: <FaDocker />,
  Django: <SiDjango />,
  Perl: <SiPerl />,
  Make: <SiGnu />,
  JavaScript: <SiJavascript />,
  Bootstrap: <FaBootstrap />,
  Mamba: <SiAnaconda />,
  "GitHub Actions": <SiGithubactions />,
  Render: <SiRender />,
  "NCBI Entrez API": <TbApi />,
  "NCBI SRA Toolkit": <FaToolbox />,
  WDL: <PiBracketsCurlyBold />,
  Nextflow: <FcWorkflow />,
  "Terra.bio (GCP)": <SiGooglecloud />,
  TensorFlow: <SiTensorflow />,
  "scikit-learn": <SiScikitlearn />,
};

const Projects = () => (
  <section className="section-container">
    <h2 className="centered-header">Projects</h2>
    <div className="projects-grid">
      {projects.map((project, index) => (
        <div key={index} className="project-card card">
          <h3 className="project-title">
            {project.name}
            {project.demo && (
              <a
                href={project.demo}
                target="_blank"
                rel="noopener noreferrer"
                className="project-title-link has-tooltip"
                data-tooltip={project.coldStartNote || "Demo"}
                aria-label={`${project.name} demo`}
              >
                <FaExternalLinkAlt />
              </a>
            )}
            {project.pypi && (
              <a
                href={project.pypi}
                target="_blank"
                rel="noopener noreferrer"
                className="project-title-link has-tooltip"
                data-tooltip="PyPI"
                aria-label={`${project.name} on PyPI`}
              >
                <FaExternalLinkAlt />
              </a>
            )}
            {project.repo && (
              <a
                href={project.repo}
                target="_blank"
                rel="noopener noreferrer"
                className="project-title-link has-tooltip"
                data-tooltip="Source"
                aria-label={`${project.name} source`}
              >
                <FaGithub />
              </a>
            )}
          </h3>
          <p className="project-description">{project.description}</p>
          <div className="project-technologies">
            {project.technologies.map((tech, idx) => {
              const icon = technologyIcons[tech];
              return (
                <span
                  key={idx}
                  className="technology-icon-wrapper"
                  title={tech}
                >
                  {icon}
                </span>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  </section>
);

export default Projects;
